version: 2.1

orbs:
  node: circleci/node@4.7.0
  
defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: snapcore/snapcraft:edge

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Update index
          command: apt update
          
      - run:
          name: Build snap
          command: snapcraft

      - persist_to_workspace:
          root: ~/workspace
          paths: [ '*.snap' ]
          
  release:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - persist_to_workspace:
          root: .
          paths:
            - .
      - attach_workspace:
          at: ~/workspace
          
      - run:
          name: Install prerequisites
          command: |
            sudo apt update
            apt install -y openssl nodejs

      - run:
          name: Decrypt credentials
          command: |
            openssl aes-256-cbc -d \
              -in .circleci/credentials.enc \
              -out credentials \
              -k $SNAPCRAFT_CREDENTIALS_KEY

      - run:
          name: Authenticate snapcraft
          command: snapcraft login --with credentials

      - run:
          name: Push/release snap
          command: snapcraft push *.snap --release edge
  test:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run test with coverage
          command: npm run test -- --coverage
      - persist_to_workspace:
          root: .
          paths:
            - .
  
  code-coverage:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - attach_workspace: 
          at: .
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
      - run:
          name: Make coverage report
          command: ./tmp/cc-test-reporter format-coverage -t lcov -o tmp/codeclimate.frontend.json coverage/lcov.info
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.frontend.json
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 2 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json

workflows:
  test:
    when:
      matches:
        pattern: "^(?!master|develop|release).*$"
        value: << pipeline.git.branch >>
    jobs:
      - test

  coverage:
    when:
      equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - test
      - code-coverage:
          requires:
            - test

  deploy:
    when:
      equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - build
      - release:
          requires:
            - build