name: bluedis
title: Bluedis
base: core18
version: '0.2.0'
architectures: [amd64, i386]
summary: An elegant Redis interface
description: |
  This project was made aiming local debugging of Redis instances.
  Check the roadmap of this project in the repository described below.

  Hope you enjoy as much as I did making this for you!
  Checkout the GitHub repository for further information.

  https://github.com/ghanizadev/bluedis
grade: stable
confinement: strict
icon: snap/local/icon.png

apps:
  bluedis:
    command: bin/Bluedis --no-sandbox
    extensions: [gnome-3-34]
    plugs:
    - browser-support
    - network
    - network-bind
    environment:
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  bluedis:
    plugin: nil
    source: .
    override-build: |
      cp -rv "$SNAPCRAFT_PART_BUILD"/out/Bluedis-* "$SNAPCRAFT_PART_INSTALL"
      mv "$SNAPCRAFT_PART_INSTALL"/Bluedis-* "$SNAPCRAFT_PART_INSTALL"/bin
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4