name: bluedis
title: Bluedis
base: core20
version: "0.2.4"
architectures: [amd64, i386]
summary: An elegant Redis interface
description: |
  This project was made aiming local debugging of Redis instances.
  Check the roadmap of this project in the repository described below.

  Hope you enjoy as much as I did making this for you!
  Checkout the GitHub repository for further information.

  https://github.com/ghanizadev/bluedis
grade: devel
confinement: strict
icon: snap/local/icon.png

apps:
  bluedis:
    command: bin/Bluedis
    extensions: [gnome-3-38]
    plugs:
      - browser-support
      - network
      - network-bind
      - desktop
      - desktop-legacy

environment:
  TMPDIR: $XDG_RUNTIME_DIR

parts:
  bluedis:
    source: .
    plugin: npm
    build-snaps: [node/16/stable]
    npm-node-version: "8.x"
    build-packages:
      - cargo
      - rustc
      - libssl-dev
      - build-essential
      - libgtk-3-dev
      - libwebkit2gtk-4.0-37
    override-build: |
      npm run tauri build -- --bundles none
      mkdir -p "$SNAPCRAFT_PART_INSTALL/bin"
      cp "$SNAPCRAFT_PART_BUILD/src-tauri/target/release/bluedis" "$SNAPCRAFT_PART_INSTALL/bin"
      mv "$SNAPCRAFT_PART_INSTALL/bin/bluedis" "$SNAPCRAFT_PART_INSTALL/bin/Bluedis"
