name: ghanizadev/bluedis/develop
on:
  push:
    branches:
      - develop

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
      - name: Generate App coverage
        run: |-
          cargo tarpaulin --verbose --out lcov --output-dir ${{github.workspace}}/coverage --manifest-path ${{github.workspace}}/src-tauri/Cargo.toml && \
          mv ${{github.workspace}}/coverage/lcov.info ${{github.workspace}}/coverage/lcov.app.info
      - name: Generate UI coverage
        run: |-
          npm run coverage && \
          mv ${{github.workspace}}/coverage/lcov.info ${{github.workspace}}/coverage/lcov.ui.info
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ad33fa5dde6dbc4859527ffc8bef376ad567d031b77b3d6291e712dc0de640bf
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov*.info:lcov

  build-tauri-app:
    runs-on: ubuntu-latest
    needs:
      - coverage
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install prerequisites
        run: |-
          sudo apt update && \
          sudo apt install -y libwebkit2gtk-4.0-dev \
          build-essential \
          curl \
          wget \
          libssl-dev \
          libgtk-3-dev \
          squashfs-tools \
          libgtksourceview-3.0-dev \
          libappindicator3-dev \
          lld \
          llvm \
          nsis \
          xfce4 \
          fakeroot \
          libclang-dev && \
          sudo apt-get clean
      - name: Build the app
        uses: tauri-apps/tauri-action@v0
