name: ghanizadev/bluedis/release
on:
  push:
    branches:
      - feat/ci-release

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install prerequesites
        run: |-
          sudo apt update && \
          sudo apt install -y libwebkit2gtk-4.0-dev \
          build-essential \
          curl \
          wget \
          libssl-dev \
          libgtk-3-dev \
          squashfs-tools \
          libgtksourceview-3.0-dev \
          libappindicator3-dev \
          lld \
          llvm \
          nsis \
          xfce4 \
          fakeroot \
          libclang-dev && \
          sudo apt-get clean
      - name: Install node_modules
        run: npm ci
      - name: Install Tauri CLI
        run: cargo install tauri-cli
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        with:
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: 'Bluedis v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: true
          prerelease: false
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md